[package]
name = "day-aoc"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.10.5"
nom = "7.1.1"
aoc_utils = { path = "../../aoc_utils" }

[profile.release]
lto = true
codegen-units = 1