[package]
name = "day-aoc"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.12"
nom = "7.1"
rayon = "1.8"
aoc_utils = { path = "../../aoc_utils" }

[profile.release]
lto = true
codegen-units = 1
