[package]
name = "day-aoc"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.12"
either = "1.9"
aoc_utils = { path = "../../aoc_utils" }

[dev-dependencies]
rstest = "0.18"

[profile.release]
lto = true
codegen-units = 1
